monolog:
    channels: ['bilan', 'ebook', 'email']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        
        bilan:
            type: rotating_file
            path: "%kernel.logs_dir%/bilan.log"
            level: info
            max_files: 10
            channels: ["bilan"]
        
        ebook:
            type: rotating_file
            path: "%kernel.logs_dir%/ebook.log"
            level: info
            max_files: 10
            channels: ["ebook"]
        
        email:
            type: rotating_file
            path: "%kernel.logs_dir%/email.log"
            level: info
            max_files: 10
            channels: ["email"]
            
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]